---
title: "Overview of pathway network databases"
author: "Kim Jablonski, Martin Pirkl"
date: "`r Sys.Date()`"
graphics: yes
output: BiocStyle::pdf_document
vignette: >
    %\VignetteIndexEntry{dce}
    %\VignetteEngine{knitr::knitr}
    %\VignetteEncoding{UTF-8}
---

# Introduction

# Installation and loading
```{r global_options, include=FALSE}
knitr::opts_chunk$set(
    message=FALSE, out.width="\\textwidth", fig.align="center",
    strip.white=TRUE, warning=FALSE, tidy=TRUE,
    fig.height = 4, fig.width = 8, error=FALSE
)
```

Install the package with the Bioconductor manager package.

```{r, eval = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install("dce")
```

Load the package with the library function.

```{r}
library(tidyverse)

library(dce)

set.seed(42)
```

```{r}
df_info <- get_pathway_info(
    database_list=c("kegg", "biocarta", "nci", "panther", "pharmgkb"), # only use "small" databases in this example
    include_network_statistics = TRUE
)

df_info %>%
    head
```

# Pathway database overview

We provide access to the following topological pathway databases using [graphite](https://bioconductor.org/packages/release/bioc/html/graphite.html):

```{r}
df_info %>%
  count(database) %>%
  arrange(desc(n))
```

```{r}
df_info %>%
  ggplot(aes(x = node_num)) +
    geom_histogram() +
    facet_wrap(~ database, scales = "free") +
    theme_minimal()
```

# Session information

```{r}
sessionInfo()
```

# References:
