---
title: "Pathway enrichment by differential causal effects."
author: "Martin Pirkl"
date: "`r Sys.Date()`"
graphics: yes
output: BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{nempi}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(message=FALSE, out.width="125%", fig.align="center",
                      strip.white=TRUE, warning=FALSE, tidy=TRUE,
                      fig.height = 4, fig.width = 8, error=FALSE)
fig.cap0 <- "Boxplots of simulation results."
```

# Introduction

In this vignette we conduct a simulation study. This study shows that we can recover differential causal effects with high accuracy compared to other methods. First, we install and load the package. Make sure to adjust the paths through the vignette.

```{r, eval=FALSE}
library(dce)
library(tidyverse); library(purrr); library(graph); library(pcalg); library(assertthat); library(igraph); library(matlib); library(nem); library(mnem); library(expm); library(Linnorm); library(MASS)
```

```{r, fig.height = 4, fig.width = 14, eval=FALSE}
## local test parameters:
n <- 100 # genes
m <- c(100, 100) # samples: wt and mut
runs <- 1
perturb <- 0 # add (positive fraction) or remove (negative) edges
p <- "runif" # edge probability
bootstrap <- c(0, "NB", "Gaus") # number of bootstrap runs for the methods
truepos <- 1 # fraction of true positive effects
test <- 1 # number of permutations for empirical p-value

## fixed parameters:
method <- "p" # correlation accuracy
mu <- 10 # mean
sd <- 10000 # standard deviation
lB <- c(-0.1,0) # negative effects intervall
uB <- c(0,0.1) # positive effects intervall

source("~/Documents/CausalPathways/dce/R/simulations.R"); source("~/Documents/CausalPathways/dce/R/main.R"); source("~/Documents/CausalPathways/dce/R/utils.R"); source("~/Documents/CausalPathways/dce/R/data_simulation.R")

set.seed(9427)
simRes <- simDce(n,m,runs,mu=mu,sd,c(lB,uB),truepos,perturb,method,p,bootstrap=bootstrap,verbose=TRUE,test=test,partial=0)

col <- rgb(c(0.5,1,0,0.1),c(0.5,0,0,0.1),c(0.5,0,1,0.1),0.75)
plot.dceSim(simRes, col = col, border = col, showMeth = c(2,3,1), showFeat = c(2,1,3,6), methNames = c("Neg. Binomial", "correlation", "random"))
```

```{r}
## testing:

beta <- 0.5
set.seed(42)
A <- rnbinom(1000, size=Inf, mu=10)
B <- rnbinom(1000, size=Inf, mu=exp(beta * scale(A, scale = FALSE))) # link function keeps mu positive, exp can lead to extreme values

estimateTheta(matrix(A, 1000))
estimateTheta(matrix(B, 1000))

summary(A)
summary(B)

glm.fun(B ~ A)

lib.factor <- sample(1:10, 1000, replace=TRUE)

A.s <- A * lib.factor
B.s <- B * lib.factor

lib.size <- A.s + B.s

# helper function
glm.fun <- function(...) {
  glm2::glm2(..., family = MASS::negative.binomial(theta=100, link="log"), control=list(maxit=1000))
}

# fit models
glm.fun(B ~ A) # works fine (no library size effect)
glm.fun(B.s ~ A.s) # gives useless result (sometimes crashes)
glm.fun(B.s ~ A.s * factor(lib.factor)) # works fine (but `lib.factor` is ground truth)
glm.fun(B.s ~ A.s * lib.size) #

```
```{r, eval=FALSE}
## get keggraph:
library(KEGGgraph)
library(KEGGREST)
pws <- keggList("pathway", "hsa")
ensembl = biomaRt::useMart("ensembl",dataset="hsapiens_gene_ensembl")
phis <- list()
custom.edge.propagation <- function(graph) {
    if (class(graph) == "graphNEL") {
        adj <- as(graph, "matrix")
    }
    adj.tc <- mnem:::mytc(adj)
    childcount <- apply(adj.tc, 1, sum)
    parentcount <- apply(adj.tc, 2, sum)
    adj.order <- order(childcount - parentcount, decreasing = TRUE)
    adj <- adj[adj.order, adj.order]
    for (j in (1:nrow(adj))[-grep("^hsa", rownames(adj))]) {
        parents <- which(adj[, j] == 1)
        children <- which(adj[j, ] == 1)
        for (p in parents) {
            adj[p, children] <- 1
        }
    }
    adj <- adj[grep("^hsa", rownames(adj)),
               grep("^hsa", colnames(adj))]
    if (class(graph) == "graphNEL") {
        adj <- as(adj, "graphNEL")
    }
    return(adj)
}
for (i in 1:length(pws)) {
    pwname <- gsub("path:", "", names(pws)[i])
    pwurl <- getKGMLurl(pwname)
    graph <- parseKGML2Graph(pwurl, genesOnly = FALSE)
    adj <- mnem:::graph2adj(graph)
    if (length(grep("^hsa", rownames(adj))) == 0) {
        next()
    }
    if (length(grep("^hsa", rownames(adj))) == 1) {
        adj <- adj[grep("^hsa", rownames(adj)), grep("^hsa", rownames(adj))]
        next()
    }
    graph <- custom.edge.propagation(graph)
    adj <- mnem:::graph2adj(graph)
    rownames(adj) <- colnames(adj) <- translateKEGGID2GeneID(rownames(adj))
    # genes <- biomaRt::getBM(attributes=c('hgnc_symbol', 'entrezgene_id'),
    #     filters = 'entrezgene_id',
    #     values = rownames(adj),
    #     mart = ensembl, useCache = FALSE)
    library(org.Hs.eg.db)
    library(dplyr)
    df.tmp <- AnnotationDbi::select(
    org.Hs.eg.db,
    keys=rownames(adj), keytype="ENTREZID",
    columns=c("ENTREZID", "ENSEMBL", "SYMBOL")
    ) %>%
    distinct(ENTREZID, .keep_all=TRUE)
    rownames(adj) <- colnames(adj) <- df.tmp$SYMBOL
    phis[[i]] <- adj
    names(phis)[i] <- pwname
}
saveRDS(phis, file = "pathways.rds")

```


```{r, eval=FALSE}
df.expr <- readr::read_csv("~/Documents/CausalPathways/tcga_pipeline/pipeline_run/tcga_data/TCGA-BRCA/expression_matrix.csv") %>% textshape::column_to_rownames("gene")
df.classi <- readr::read_csv("~/Documents/CausalPathways/tcga_pipeline/pipeline_run/tcga_data/TCGA-BRCA/case_classifications.csv")

source("~/Documents/CausalPathways/dce/R/simulations.R"); source("~/Documents/CausalPathways/dce/R/main.R"); source("~/Documents/CausalPathways/dce/R/utils.R"); source("~/Documents/CausalPathways/dce/R/data_simulation.R")

## real data:
brca <- read.csv("~/Documents/CausalPathways/tcga_pipeline/pipeline_run/tcga_data/TCGA-BRCA/expression_matrix.csv")
brca.info <- read.csv("~/Documents/CausalPathways/tcga_pipeline/pipeline_run/tcga_data/TCGA-BRCA/case_classifications.csv")

## alt kegg:
phis <- readRDS("pathways.rds")
brca.kegg <- phis[[grep("05224", names(phis))]]
genes <- which(apply(brca.kegg, 1, sum) > 0 | apply(brca.kegg, 2, sum) > 0)
brca.kegg <- brca.kegg[genes, genes]
brca.kegg <- rowsum(brca.kegg, rownames(brca.kegg))
brca.kegg <- t(rowsum(t(brca.kegg), colnames(brca.kegg)))

ensembl = biomaRt::useMart("ensembl",dataset="hsapiens_gene_ensembl")
ens_genes <- biomaRt::getBM(attributes=c('ensembl_gene_id','hgnc_symbol'),
      filters = 'hgnc_symbol',
      values = rownames(brca.kegg),
      mart = ensembl)
brca.adj <- brca.kegg
rownames(brca.adj) <- colnames(brca.adj) <- ens_genes[which(!duplicated(ens_genes$hgnc_symbol)), 1]

# # new kegg:
# brca.kegg <- readr::read_csv("~/Documents/CausalPathways/tcga_pipeline/pipeline_run/kegg_data/hsa05224.edgelist.csv.gz")
# brca.genes <- unique(c(as.vector(brca.kegg$source), as.vector(brca.kegg$sink)))
# ensembl = biomaRt::useMart("ensembl",dataset="hsapiens_gene_ensembl")
# genes <- biomaRt::getBM(attributes=c('hgnc_symbol', 'ensembl_gene_id'),
#       filters = 'ensembl_gene_id',
#       values = rownames(brca.adj),
#       mart = ensembl)
#
# brca.genes <- sort(brca.genes[grep("ENSG", brca.genes)])
# brca.kegg <- brca.kegg[intersect(grep("ENSG", brca.kegg$source), grep("ENSG", brca.kegg$sink)), ]
# n <- length(brca.genes)
# brca.adj <- matrix(0, n, n)
# colnames(brca.adj) <- rownames(brca.adj) <- brca.genes
# a <- apply(matrix(brca.kegg$source, 1), 2, function(x) {
#     y <- which(rownames(brca.adj) %in% x)
#     return(y)
# })
# b <- apply(matrix(brca.kegg$sink, 1), 2, function(x) {
#     y <- which(colnames(brca.adj) %in% x)
#     return(y)
# })
# brca.adj[cbind(a,b)] <- 1

brca.mat <- as(brca[, -1], "matrix")
rownames(brca.mat) <- brca[, 1]
gene.median <- apply(brca.mat, 1, median)
brca.mat <- brca.mat[which(gene.median > 10), ]
theta <- estimateTheta(t(brca.mat)) # theta <- 1.527499 # brca

# set.seed(1)
# for (i in 1:10000) {
#     s1 <- sample(1:nrow(brca.mat), 1)
#     s2 <- sample(1:nrow(brca.mat), 1)
#     # theta.pw <- estimateTheta(t(brca.mat[c(s1, s2), ]))
#     theta.pw <- 10
#     glm2::glm2(brca.mat[s1, ] ~ brca.mat[s2, ], family=MASS::negative.binomial(theta=theta.pw, link=linkfun))
#     cat(paste0(".", i))
# }
# plot(brca.mat[s1, ], brca.mat[s2, ])

library(graph)
normal <- as(brca.adj, "graphNEL")
tumor <- normal
theta <- theta # NULL
control <- glm.control(epsilon = 1e-8, maxit = 100, trace = FALSE)
dn <- t(brca.mat[, which(brca.info$definition %in% "Solid Tissue Normal")])
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor")])
dce <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor" & brca.info$tumor_stage %in% "stage i")])
dceI <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor" & brca.info$tumor_stage %in% "stage ii")])
dceII <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor" & brca.info$tumor_stage %in% "stage iii")])
dceIII <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor" & brca.info$tumor_stage %in% "stage iv")])
dceIV <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor" & brca.info$tumor_stage %in% "stage x")])
dceX <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)
dt <- t(brca.mat[, which(brca.info$definition %in% "Primary solid Tumor" & brca.info$tumor_stage %in% "not reported")])
dceNR <- compute_differential_causal_effects(normal, dn, tumor, dt, theta = theta, control = control)



stage <- list(All = dce, I = dceI, II = dceII, III = dceIII, IV = dceIV, X = dceX, NR = dceNR)
pdf("~/Documents/temp.pdf", width = 50, height = 50)
for (i in 2:4) {#1:length(stage)) {
    print(names(stage)[i])
    dceTmp <- stage[[i]]
    print(compute_enrichment(normal, dce = dceTmp)$p.value)

    rownames(brca.adj) <- colnames(brca.adj) <- ens_genes[which(!duplicated(ens_genes$hgnc_symbol)), 2]

    brca.dnf <- which(brca.adj == 1, arr.ind = TRUE)
    brca.dnf <- apply(brca.dnf, 1, function(x) {
        y <- paste0(rownames(brca.adj)[x[1]], "=", colnames(brca.adj)[x[2]])
        return(y)
    })
    brca.dnf <- brca.dnf[grep("=", brca.dnf)]
    brca.freq <- dceTmp$dce[which(dceTmp$dce != 0)]*100
    brca.col <- abs(brca.freq)/max(abs(brca.freq))
    edgecol <- rgb(brca.col, 0, max(brca.col) - brca.col, 0.5)
    source("~/Documents/mnem/R/mnems.r")
    #mnem::
    print(max(10^(abs(brca.freq))-0.9))
    plotDnf(brca.dnf, edgecol = edgecol, edgewidth = 10^(abs(brca.freq))-0.9, edgelabel = (round(brca.freq, 2)*100), main = names(stage)[i])
}
dev.off()
```

```{r, eval=FALSE}

dosave <- 0 # adjust this as needed
if (dosave) {
    for (filen in 1:100) {
        # adjust path
        filename <- paste("~/CausalPathways/simulations/dce", n,
                          paste(m, collapse = "_"), sd, perturb,
                          p, lB[1], uB[2], filen, ".rda", sep = "_")
        if (!file.exists(filename)) {
            break()
        }
    }
    save(simRes, file = filename)
}

p2 <- 0.1
normal <- create_random_DAG(n, p2, lB, uB)
tumor <- resample_edge_weights(normal, lB, uB, truepos)
dn <- simulate_data_old(normal, m[2], normpars = c(mu,sd), errDist=errDist)
dt <- simulate_data_old(tumor, m[1], normpars = c(mu,sd), errDist=errDist)
dcei <- compute_differential_causal_effects(normal, dn,tumor, dt, method = "full",errDist = errDist)

```

# Stuff to be deleted pre-publication

```{bash, eval=FALSE}
module add /cluster/apps/modules/modulefiles/new
module load python/3.7.1
module load bioconductor/3.6
module load curl/7.49.1
module load gmp/5.1.3
module load texlive

scp CausalPathways/dce/R/main.r euler.ethz.ch:CausalPathways/dce/R/main.R
scp CausalPathways/dce/R/utils.r euler.ethz.ch:CausalPathways/dce/R/utils.R
scp CausalPathways/dce/R/simulations.r euler.ethz.ch:CausalPathways/dce/R/simulations.R
scp CausalPathways/dce/vignettes/simulations.Rmd euler.ethz.ch:CausalPathways/dce/vignettes/simulations.Rmd

ram=1000

rm error.txt

rm output.txt

rm .RData

queue=4

genes=100
perturb=0 # negative or positive fraction of edges to delete or add
runs=1
tumor=200 # samples
normal=200
bstrap=0 # if > 0 runs bootstrapping on the data
truepos=1 # if < 1, sets some causal effects equal between the tumor and normal
test=0 # number of permutations for empricial p-value
dosave=1; # save the run(s)

## knit several times to accumulate several runs
bsub -M ${ram} -q normal.${queue}h -n 1 -e error.txt -o output.txt \
	-R "rusage[mem=${ram}]" \
	"~/R/bin/Rscript --silent --no-save \
	-e \"e <- new.env(parent = globalenv()); assign('genes', ${genes}, envir = e); \
	assign('tumor', ${tumor}, envir = e); assign('normal', ${normal}, envir = e); \
	assign('runs', ${runs}, envir = e); assign('perturb', ${perturb}, envir = e); \
	assign('bstrap', ${bstrap}, envir = e); \
	assign('dosave', ${dosave}, envir = e); \
	assign('truepos', ${truepos}, envir = e); assign('test', ${test}, envir = e); \
    knitr::knit2pdf('~/CausalPathways/dce/vignettes/simulations.Rmd',
    out = '~/CausalPathways/simulations.tex', envir = e, compiler = 'latex')\""

```


```{r, eval=FALSE}
dosave <- 0 # adjust this as needed
if (dosave) {
    library(abind)
    simRes2 <- NULL
    for (filen in 1:100) {
        filename <- paste("~/CausalPathways/simulations/dce", n, # adjust path
                          paste(m, collapse = "_"), sd, perturb,
                          p, lB[1], uB[2], filen, ".rda", sep = "_")
        if (file.exists(filename)) {
            load(filename)
            simRes2$acc <- abind(simRes2$acc, simRes$acc, along = 1)
            simRes2$gtnFeat <- abind(simRes2$gtnFeat, simRes$gtnFeat, along = 1)
            cat(paste0(filen, "."))
        }
    }
    simRes <- simRes2
    class(simRes) <- "dceSim"
}
```

Plot the results.

```{r, fig.cap=fig.cap0, eval=FALSE}
col <- rgb(c(0.5,1,0,0.1),c(0.5,0,0,0.1),c(0.5,0,1,0.1),0.75)
plot.dceSim(simRes, col = col, border = col, showMeth = c(2,5,3,6,1,4),
            showFeat = c(1,4,5,6,3),
            methNames = c("basic", "basic\n bootstrap",
                          "full", "full\n bootstrap", "random", "correlation"))

## correlated with network features:
## print(cor(acc[,,1], gtnfeat[,2]))

## ## conversion between data.frame and array
## acc.df <- as.data.frame.table(acc)
## acc.arr <- xtabs(Freq ~ runs + methods + metrics, acc.df)
```

```{r}
sessionInfo()
```
